################################################################################################################################
#                                                        TEST                                                                  #
################################################################################################################################

test:
  stage: test
  script:
    - echo "Placeholder for running tests"
  rules:
    - if: "$CI_COMMIT_BRANCH =~ /^feature.*$/ || $CI_COMMIT_BRANCH =~ /^fix.*$/"
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

################################################################################################################################
#                                                        DEPLOY - PROD                                                         #
################################################################################################################################

deploy-aws:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == "development"'
  script:
    - /busybox/echo "{\"credHelpers\":{\"${DOCKER_REGISTRY_AWS}\":\"ecr-login\"}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${DOCKER_REGISTRY_AWS}/${DOCKER_IMAGE_AWS}:latest"
      --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      --build-arg BUILD_VERSION=${CI_COMMIT_SHORT_SHA}
      --build-arg REVISION_ID=$CI_COMMIT_SHORT_SHA
      --build-arg CI_PROJECT_NAME=$CI_PROJECT_NAME
      --build-arg CI_PROJECT_NAME=$CI_PROJECT_NAME
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
